apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-deployment
  labels:
    app: goweb-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: goweb-app
  template:
    metadata:
      labels:
        app: goweb-app
    spec:
      containers:
      - name: goweb-app
        image: kp3073/go-web-app:3a87fc0832665a32cb68a93ca68e4695e2f77bc0
        ports:
        - containerPort: 8080
