name: Docker Image CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  
  build:
    
    runs-on: self-hosted
    
    steps:
    - uses: actions/checkout@v4
      
    - name: Print all environment variables
      run: printenv
      
    - name: Build the Docker image
      run: |
        $env
        docker build -t kp3073/go-web-app:${GITHUB_SHA} .
      
    - name: Push the Docker image
      run: |
        docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
        docker push kp3073/go-web-app:${GITHUB_SHA}
        